DROP TABLE IF EXISTS FILM_GENRES;
DROP TABLE IF EXISTS FILM_DIRECTORS;
DROP TABLE IF EXISTS FILM_WHO_LIKED_USERS;
DROP TABLE IF EXISTS REVIEW_RATINGS;
DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS FILMS;
DROP TABLE IF EXISTS DIRECTORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS RATINGS;
DROP TABLE IF EXISTS FRIENDSHIPS;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS ratings
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration     INTEGER,
    description  VARCHAR,
    name         VARCHAR,
    RELEASE_DATE DATE,
    rating_id    INTEGER,
    FOREIGN KEY (rating_id) REFERENCES ratings (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  INTEGER,
    genre_id VARCHAR,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR,
    login    VARCHAR,
    name     VARCHAR,
    birthday DATE,
    CONSTRAINT email_idx UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS film_who_liked_users
(
    film_id           INTEGER,
    who_liked_user_id INTEGER,
    PRIMARY KEY (film_id, who_liked_user_id),
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (who_liked_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendships
(
    user_id   INTEGER,
    friend_id INTEGER,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE,
    CHECK user_id <> friend_id
);

CREATE TABLE IF NOT EXISTS reviews
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER,
    film_id     INTEGER,
    content     VARCHAR NOT NULL,
    is_positive BOOLEAN NOT NULL,

    CONSTRAINT fk_reviews_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_film_id FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_ratings
(
    user_id   INTEGER REFERENCES users (id) ON DELETE CASCADE,
    review_id INTEGER REFERENCES reviews (id) ON DELETE CASCADE,
    is_like   BOOLEAN,
    PRIMARY KEY (user_id, review_id)
);

CREATE TABLE IF NOT EXISTS directors
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors
(
    director_id INTEGER,
    film_id     INTEGER,

    CONSTRAINT pk_film_directors PRIMARY KEY (director_id, film_id),
    CONSTRAINT fk_film_directors_director_id FOREIGN KEY (director_id) REFERENCES directors (id) ON DELETE CASCADE,
    CONSTRAINT fk_film_directors_film_id FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER,
    type       VARCHAR,
    operation  VARCHAR,
    entity_id  INTEGER  NOT NULL,
    event_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_event_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);